import { supabaseAdmin } from './config/supabase';

const defaultCategories = [
  { id: 'appartements-moins-chers', title: 'Appartements moins chers', img: '/images/pexels-fotoaibe-1571460.jpg', alt: 'Appartement lumineux au meilleur prix', market: 'BJ' },
  { id: 'appartements-premium', title: 'Appartements premium', img: '/images/pexels-donaldtong94-189333.jpg', alt: 'Appartement premium avec salon spacieux', market: 'BJ' },
  { id: 'villas-premium', title: 'Villas premium', img: '/images/pexels-artbovich-7214173.jpg', alt: 'Villa premium avec jardin', market: 'BJ' },
  { id: 'hotel', title: 'Hôtel', img: '/images/pexels-artbovich-7045712.jpg', alt: 'Suite hôtelière avec vue mer', market: 'BJ' },
  { id: 'ci-chambres-moins-chères', title: 'Chambres moins chères', img: '/images/pexels-fotoaibe-1571460.jpg', alt: 'Chambre simple et abordable', market: 'CI' },
  { id: 'ci-chambres-premium', title: 'Chambres premium', img: '/images/pexels-artbovich-6782567.jpg', alt: 'Chambre premium bien équipée', market: 'CI' },
  { id: 'ci-appartements', title: 'Appartements', img: '/images/pexels-artbovich-7214173.jpg', alt: 'Appartement spacieux', market: 'CI' },
  { id: 'ci-hotel', title: 'Hôtel', img: '/images/pexels-artbovich-7045712.jpg', alt: 'Suite hôtelière', market: 'CI' },
];

const defaultRooms = [
  {
    id: 'familial-quartier-des-arts', title: 'Familial — Quartier des arts', subtitle: 'Appartement spacieux idéal pour les familles',
    info: '68 m² · 2 chambres · Balcon', price: '660', price_num: 660, price_unit: '/ mois',
    img: '/images/pexels-artbovich-6782567.jpg', alt: 'Familial, Quartier des arts',
    images: ['/images/pexels-artbovich-6782567.jpg', '/images/pexels-artbovich-7045712.jpg'],
    description: 'Appartement familial lumineux situé au cœur du quartier des arts.', capacity: '4 personnes',
    category: 'appartements-moins-chers', market: 'BJ', pays: 'Bénin', ville: 'Cotonou', quartier: 'Quartier des arts',
    chambres: 2, douches: 1, disponible: true, date_dispo: '2026-09-15',
    conditions: 'Caution : 1 mois de loyer, Durée minimale : 6 mois',
  },
  {
    id: 'jardin-front-de-mer', title: 'Jardin — Front de mer', subtitle: 'Maison avec jardin en bord de mer',
    info: '72 m² · 2 chambres · Jardin', price: '690', price_num: 690, price_unit: '/ mois',
    img: '/images/pexels-artbovich-7045712.jpg', alt: 'Jardin, Front de mer',
    images: ['/images/pexels-artbovich-7045712.jpg', '/images/pexels-artbovich-7214173.jpg'],
    description: 'Maison avec jardin privatif en bord de mer.', capacity: '4 personnes',
    category: 'appartements-premium', market: 'BJ', pays: 'Bénin', ville: 'Cotonou', quartier: 'Front de mer',
    chambres: 2, douches: 2, disponible: true, date_dispo: '2026-09-10',
    conditions: 'Caution : 2 mois de loyer, Durée minimale : 12 mois',
  },
  {
    id: 'lumineux-centre-ville', title: 'Lumineux — Centre-ville', subtitle: 'Appartement moderne en plein centre',
    info: '65 m² · 2 chambres · Balcon', price: '670', price_num: 670, price_unit: '/ mois',
    img: '/images/pexels-artbovich-7214173.jpg', alt: 'Lumineux, Centre-ville',
    images: ['/images/pexels-artbovich-7214173.jpg', '/images/pexels-artbovich-6782567.jpg'],
    description: 'Appartement lumineux au cœur de la ville.', capacity: '4 personnes',
    category: 'appartements-moins-chers', market: 'BJ', pays: 'Bénin', ville: 'Cotonou', quartier: 'Centre-ville',
    chambres: 2, douches: 1, disponible: true, date_dispo: '2026-09-20',
    conditions: 'Caution : 1 mois de loyer, Durée minimale : 6 mois',
  },
  {
    id: 'vue-mer-corniche', title: 'Vue mer — Corniche', subtitle: 'Appartement avec vue panoramique',
    info: '70 m² · 2 chambres · Terrasse', price: '710', price_num: 710, price_unit: '/ mois',
    img: '/images/pexels-donaldtong94-189333.jpg', alt: 'Vue mer, Corniche',
    images: ['/images/pexels-donaldtong94-189333.jpg', '/images/pexels-artbovich-7045712.jpg'],
    description: 'Appartement premium sur la corniche avec vue panoramique.', capacity: '4 personnes',
    category: 'appartements-premium', market: 'BJ', pays: 'Bénin', ville: 'Cotonou', quartier: 'Corniche',
    chambres: 2, douches: 2, disponible: true, date_dispo: '2026-10-01',
    conditions: 'Caution : 2 mois de loyer, Durée minimale : 12 mois',
  },
  {
    id: 'calme-peripherie', title: 'Calme — Périphérie', subtitle: 'Appartement paisible en périphérie',
    info: '62 m² · 2 chambres · Parking', price: '640', price_num: 640, price_unit: '/ mois',
    img: '/images/pexels-fotoaibe-1571460.jpg', alt: 'Calme, Périphérie',
    images: ['/images/pexels-fotoaibe-1571460.jpg', '/images/pexels-artbovich-6283961.jpg'],
    description: 'Appartement calme en périphérie.', capacity: '4 personnes',
    category: 'appartements-moins-chers', market: 'BJ', pays: 'Bénin', ville: 'Cotonou', quartier: 'Périphérie',
    chambres: 2, douches: 1, disponible: false, date_dispo: '2026-12-01',
    conditions: 'Caution : 1 mois de loyer, Durée minimale : 6 mois',
  },
  {
    id: 'suite-prestige-front-de-mer', title: 'Suite Prestige — Front de mer', subtitle: 'Suite luxe avec salon séparé',
    info: '38 m² · 3 pers. · Petit-déj. inclus', price: '119', price_num: 119, price_unit: '/ nuit',
    img: '/images/pexels-artbovich-6758771.jpg', alt: 'Suite Prestige, Front de mer',
    images: ['/images/pexels-artbovich-6758771.jpg', '/images/pexels-artbovich-6315808.jpg'],
    description: 'Suite prestige en front de mer avec salon séparé.', capacity: '3 personnes',
    category: 'hotel', market: 'BJ', pays: 'Bénin', ville: 'Cotonou', quartier: 'Front de mer',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-10',
    conditions: 'Réservation en ligne, Annulation gratuite 48h avant',
  },
  {
    id: 'suite-vue-mer-top-floor', title: 'Suite Vue Mer — Top floor', subtitle: 'Suite au dernier étage avec terrasse',
    info: '42 m² · 3 pers. · Terrasse privée', price: '135', price_num: 135, price_unit: '/ nuit',
    img: '/images/pexels-artbovich-6315808.jpg', alt: 'Suite Vue Mer, Top floor',
    images: ['/images/pexels-artbovich-6315808.jpg', '/images/pexels-artbovich-6758771.jpg'],
    description: 'Suite au dernier étage avec terrasse privée.', capacity: '3 personnes',
    category: 'hotel', market: 'BJ', pays: 'Bénin', ville: 'Cotonou', quartier: 'Front de mer',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-10',
    conditions: 'Réservation en ligne, Annulation gratuite 48h avant',
  },
  {
    id: 'suite-charme-centre-ville', title: 'Suite Charme — Centre-ville', subtitle: 'Suite élégante en centre-ville',
    info: '35 m² · 2 pers. · Balcon', price: '110', price_num: 110, price_unit: '/ nuit',
    img: '/images/pexels-artbovich-6283961.jpg', alt: 'Suite Charme, Centre-ville',
    images: ['/images/pexels-artbovich-6283961.jpg', '/images/pexels-artbovich-6758771.jpg'],
    description: 'Suite charme au cœur de la ville.', capacity: '2 personnes',
    category: 'hotel', market: 'BJ', pays: 'Bénin', ville: 'Porto-Novo', quartier: 'Centre-ville',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-12',
    conditions: 'Réservation en ligne, Annulation gratuite 24h avant',
  },
  {
    id: 'suite-familiale-calme', title: 'Suite Familiale — Calme', subtitle: 'Grande suite pour famille',
    info: '50 m² · 4 pers. · 2 chambres', price: '155', price_num: 155, price_unit: '/ nuit',
    img: '/images/pexels-artbovich-6238608.jpg', alt: 'Suite Familiale, Calme',
    images: ['/images/pexels-artbovich-6238608.jpg', '/images/pexels-artbovich-6782567.jpg'],
    description: 'Grande suite familiale dans un cadre calme.', capacity: '4 personnes',
    category: 'hotel', market: 'BJ', pays: 'Bénin', ville: 'Ouidah', quartier: 'Périphérie',
    chambres: 2, douches: 2, disponible: true, date_dispo: '2026-09-18',
    conditions: 'Réservation en ligne, Annulation gratuite 48h avant',
  },
  {
    id: 'lumineux-centre-ville-studio', title: 'Lumineux — Centre-ville', subtitle: 'Studio moderne en centre-ville',
    info: '32 m² · 3e ét. asc. · DPE B', price: '430', price_num: 430, price_unit: '/ mois',
    img: '/images/pexels-artbovich-5998120.jpg', alt: 'Lumineux, Centre-ville',
    images: ['/images/pexels-artbovich-5998120.jpg', '/images/pexels-artbovich-5998117.jpg'],
    description: 'Studio lumineux au 3e étage avec ascenseur.', capacity: '2 personnes',
    category: 'appartements-moins-chers', market: 'BJ', pays: 'Bénin', ville: 'Cotonou', quartier: 'Centre-ville',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-14',
    conditions: 'Caution : 1 mois de loyer, Durée minimale : 6 mois',
  },
  {
    id: 'cosy-quartier-des-arts', title: 'Cosy — Quartier des arts', subtitle: 'Studio chaleureux et intime',
    info: '28 m² · 2e ét. · DPE C', price: '400', price_num: 400, price_unit: '/ mois',
    img: '/images/pexels-artbovich-5998117.jpg', alt: 'Cosy, Quartier des arts',
    images: ['/images/pexels-artbovich-5998117.jpg', '/images/pexels-artbovich-5998120.jpg'],
    description: 'Studio cosy au cœur du quartier des arts.', capacity: '2 personnes',
    category: 'appartements-moins-chers', market: 'BJ', pays: 'Bénin', ville: 'Porto-Novo', quartier: 'Quartier des arts',
    chambres: 1, douches: 1, disponible: false, date_dispo: '2026-11-15',
    conditions: 'Caution : 1 mois de loyer, Durée minimale : 6 mois',
  },
  {
    id: 'moderne-front-de-mer-studio', title: 'Moderne — Front de mer', subtitle: 'Studio design en bord de mer',
    info: '30 m² · 4e ét. asc. · DPE B', price: '450', price_num: 450, price_unit: '/ mois',
    img: '/images/pexels-artbovich-7214173.jpg', alt: 'Moderne, Front de mer',
    images: ['/images/pexels-artbovich-7214173.jpg', '/images/pexels-artbovich-7045712.jpg'],
    description: 'Studio moderne au 4e étage avec vue mer.', capacity: '2 personnes',
    category: 'appartements-premium', market: 'BJ', pays: 'Bénin', ville: 'Grand Popo', quartier: 'Front de mer',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-10',
    conditions: 'Caution : 1 mois de loyer, Durée minimale : 6 mois',
  },
  {
    id: 'chaleureux-peripherie-studio', title: 'Chaleureux — Périphérie', subtitle: 'Studio calme en périphérie',
    info: '26 m² · 1er ét. · DPE C', price: '380', price_num: 380, price_unit: '/ mois',
    img: '/images/pexels-artbovich-6283961.jpg', alt: 'Chaleureux, Périphérie',
    images: ['/images/pexels-artbovich-6283961.jpg', '/images/pexels-artbovich-5998117.jpg'],
    description: 'Studio chaleureux au 1er étage en périphérie.', capacity: '2 personnes',
    category: 'appartements-moins-chers', market: 'BJ', pays: 'Bénin', ville: 'Cotonou', quartier: 'Périphérie',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-10',
    conditions: 'Caution : 1 mois de loyer, Durée minimale : 6 mois',
  },
  {
    id: 'abidjan-plateau-moderne', title: 'Appartement Moderne — Plateau', subtitle: 'Appartement au cœur du quartier des affaires',
    info: '65 m² · 2 chambres · Climatisation', price: '75 000', price_num: 75000, price_unit: '/ mois',
    img: '/images/pexels-artbovich-7214173.jpg', alt: 'Appartement moderne Plateau Abidjan',
    images: ['/images/pexels-artbovich-7214173.jpg', '/images/pexels-artbovich-7045712.jpg'],
    description: 'Bel appartement moderne au cœur du Plateau.', capacity: '4 personnes',
    category: 'ci-appartements', market: 'CI', pays: "Côte d'Ivoire", ville: 'Abidjan', quartier: 'Plateau',
    chambres: 2, douches: 1, disponible: true, date_dispo: '2026-09-01',
    conditions: 'Caution : 2 mois, Durée minimale : 12 mois',
  },
  {
    id: 'abidjan-cocody-studio', title: 'Studio Élégant — Cocody', subtitle: 'Studio dans quartier résidentiel',
    info: '35 m² · 1 chambre · Meublé', price: '45 000', price_num: 45000, price_unit: '/ mois',
    img: '/images/pexels-artbovich-6782567.jpg', alt: 'Studio élégant Cocody Abidjan',
    images: ['/images/pexels-artbovich-6782567.jpg', '/images/pexels-artbovich-6758771.jpg'],
    description: 'Studio moderne situé dans le quartier résidentiel de Cocody.', capacity: '2 personnes',
    category: 'ci-chambres-premium', market: 'CI', pays: "Côte d'Ivoire", ville: 'Abidjan', quartier: 'Cocody',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-05',
    conditions: 'Caution : 2 mois, Durée minimale : 6 mois',
  },
  {
    id: 'abidjan-marcoral-ville', title: 'Villa Prestigieuse — Marcory', subtitle: 'Villa avec jardin tropical',
    info: '200 m² · 4 chambres · Jardin · Piscine', price: '250 000', price_num: 250000, price_unit: '/ mois',
    img: '/images/pexels-artbovich-6283961.jpg', alt: 'Villa prestige Marcory Abidjan',
    images: ['/images/pexels-artbovich-6283961.jpg', '/images/pexels-artbovich-6238608.jpg'],
    description: 'Magnifique villa dans le quartier huppé de Marcory.', capacity: '8 personnes',
    category: 'ci-appartements', market: 'CI', pays: "Côte d'Ivoire", ville: 'Abidjan', quartier: 'Marcory',
    chambres: 4, douches: 3, disponible: true, date_dispo: '2026-09-15',
    conditions: 'Caution : 3 mois, Durée minimale : 12 mois',
  },
  {
    id: 'abidjan-treichville-studio', title: 'Studio Tout Confort — Treichville', subtitle: 'Studio dans quartier animé',
    info: '25 m² · 1 chambre · WiFi', price: '30 000', price_num: 30000, price_unit: '/ mois',
    img: '/images/pexels-artbovich-5998120.jpg', alt: 'Studio Treichville Abidjan',
    images: ['/images/pexels-artbovich-5998120.jpg', '/images/pexels-artbovich-5998117.jpg'],
    description: 'Studio bien équipé dans le quartier animé de Treichville.', capacity: '2 personnes',
    category: 'ci-chambres-premium', market: 'CI', pays: "Côte d'Ivoire", ville: 'Abidjan', quartier: 'Treichville',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-01',
    conditions: 'Caution : 1 mois, Durée minimale : 6 mois',
  },
  {
    id: 'bouake-centre-appart', title: 'Appartement Spacieux — Bouaké Centre', subtitle: 'Appartement au cœur de la ville',
    info: '55 m² · 2 chambres · Parking', price: '35 000', price_num: 35000, price_unit: '/ mois',
    img: '/images/pexels-artbovich-6315808.jpg', alt: 'Appartement spacieux Bouaké',
    images: ['/images/pexels-artbovich-6315808.jpg', '/images/pexels-artbovich-7045712.jpg'],
    description: 'Grand appartement au centre de Bouaké.', capacity: '4 personnes',
    category: 'ci-appartements', market: 'CI', pays: "Côte d'Ivoire", ville: 'Bouaké', quartier: 'Centre',
    chambres: 2, douches: 1, disponible: true, date_dispo: '2026-09-10',
    conditions: 'Caution : 1 mois, Durée minimale : 6 mois',
  },
  {
    id: 'yamoussoukro-paix-chambre', title: 'Chambre Meublée — Quartier Paix', subtitle: 'Chambre proche de la basilique',
    info: '18 m² · 1 chambre · Meublé', price: '20 000', price_num: 20000, price_unit: '/ mois',
    img: '/images/pexels-fotoaibe-1571460.jpg', alt: 'Chambre meublée Yamoussoukro',
    images: ['/images/pexels-fotoaibe-1571460.jpg', '/images/pexels-artbovich-5998120.jpg'],
    description: 'Chambre meublée dans le quartier Paix à Yamoussoukro.', capacity: '1 personne',
    category: 'ci-chambres-moins-chères', market: 'CI', pays: "Côte d'Ivoire", ville: 'Yamoussoukro', quartier: 'Paix',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-01',
    conditions: 'Caution : 1 mois, Durée minimale : 3 mois',
  },
  {
    id: 'san-pedro-port-chambre', title: 'Chambre au Port — San-Pédro', subtitle: 'Chambre pratique près du port',
    info: '16 m² · 1 chambre · Eau courante', price: '18 000', price_num: 18000, price_unit: '/ mois',
    img: '/images/pexels-donaldtong94-189333.jpg', alt: 'Chambre port San-Pédro',
    images: ['/images/pexels-donaldtong94-189333.jpg', '/images/pexels-artbovich-6782567.jpg'],
    description: 'Chambre idéalement située près du port de San-Pédro.', capacity: '1 personne',
    category: 'ci-chambres-moins-chères', market: 'CI', pays: "Côte d'Ivoire", ville: 'San-Pédro', quartier: 'Port',
    chambres: 1, douches: 1, disponible: true, date_dispo: '2026-09-01',
    conditions: 'Caution : 1 mois, Durée minimale : 3 mois',
  },
];

async function seed() {
  console.log('Seeding categories...');
  const { error: catError } = await supabaseAdmin.from('categories').upsert(defaultCategories, { onConflict: 'id' });
  if (catError) console.error('Categories error:', catError.message);
  else console.log(`  ${defaultCategories.length} categories seeded`);

  console.log('Seeding rooms...');
  const { error: roomError } = await supabaseAdmin.from('rooms').upsert(defaultRooms, { onConflict: 'id' });
  if (roomError) console.error('Rooms error:', roomError.message);
  else console.log(`  ${defaultRooms.length} rooms seeded`);

  console.log('Done!');
}

seed();
